server:
  #debug or release
  runMode: debug
  httpPort: 8000
  readTimeout: 60
  writeTimeout: 60
database:
  type: mysql
  user: root
  password: mysql123456
  host: 43.137.50.64:3306
  name: websearch
redis:
  password: redis123456
  host: 43.137.50.64
  port: 6379